[package]
name = "calamars_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
calamars_core = { path="../calamars_core" }
front = { path = "../front" }
ariadne = "0.6.0"
clap = "4.5.51"
logos = "0.15.1"
