[package]
name = "front"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.0"
calamars_core = { path="../calamars_core" }
ariadne = "0.5.1"
clap = { version = "4.5.49", features = ["derive"] }
logos = "0.15.0"
proptest = "1.7.0"
rustyline = "17.0.2"
